#set-option -sa terminal-features ',alacritty:RGB'
set-option -a terminal-overrides ",xterm-256color:RGB"
set-option default-terminal "tmux-256color"
set-option -ga terminal-features ",alacritty:usstyle"

unbind -n MouseDown3Pane
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
#set-option -g status-style 'bg=#333333 fg=#5eacd3'
set-option -g status-style fg=colour136,bg=colour235 #yellow and base02

unbind r
bind r source-file ~/.config/tmux/tmux.conf
set -g base-index 1
set -g mouse on

set-option -g focus-events on

set-window-option -g mode-keys vi
bind -T copy-mode-vi 'v' send-keys -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-selection

bind L swap-pane -D

unbind -T copy-mode-vi MouseDragEnd1Pane

bind -r m resize-pane -Z

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# vim-like pane switching
unbind C-^
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r K resize-pane -U 5
bind -r J resize-pane -D 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

bind-key G run-shell "/usr/local/bin/tmux-back-to-vim"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# run '~/.tmux/plugins/tpm/tpm'
